<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PackageId>BlazorMHD.UI</PackageId>

    <!-- ✅ اختياري لكنه يثبت مسار _content -->
    <AssemblyName>BlazorMHD.UI</AssemblyName>
    <RootNamespace>BlazorMHD.UI</RootNamespace>

    <Version>1.0.0</Version>
    <Authors>Your Name</Authors>
    <Description>Compact Blazor UI library for admin dashboards with Tailwind and dark mode.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>


	<!-- ✅ minify فقط في Release -->
  <PropertyGroup>
    <TailwindMinify Condition="'$(Configuration)'=='Release'">--minify</TailwindMinify>
    <TailwindMinify Condition="'$(Configuration)'!='Release'"></TailwindMinify>
  </PropertyGroup>

  <ItemGroup>
    <!-- ملفات تؤثر على Tailwind -->
    <TailwindContent Include="**\*.razor" />
    <TailwindContent Include="**\*.cs" />
    <TailwindContent Include="wwwroot\css\**\*.css" />
  </ItemGroup>

  <!-- ✅ تثبيت npm مرة واحدة فقط إذا node_modules غير موجود -->
  <Target Name="TailwindInstall" BeforeTargets="Build" Condition="!Exists('$(MSBuildProjectDirectory)\node_modules')">
    <Exec Command="npm ci" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>

  <!-- ✅ يبني Tailwind فقط عند تغيّر Inputs -->
  <Target Name="TailwindBuild" BeforeTargets="Build" DependsOnTargets="TailwindInstall" Inputs="tailwind.config.js;package-lock.json;wwwroot\app.tailwind.css;@(TailwindContent)" Outputs="wwwroot\css\mhd.css">
    <Exec Command="npx tailwindcss -c ./tailwind.config.js -i ./wwwroot/app.tailwind.css -o ./wwwroot/css/mhd.css $(TailwindMinify)" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Navigation\Tabs\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Shared\Localiztion.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Localiztion.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Shared\Localiztion.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Localiztion.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<Content Update="**\package.json" CopyToPublishDirectory="Never" />
		<Content Update="**\package-lock.json" CopyToPublishDirectory="Never" />
		<Content Update="**\tailwind.config.js" CopyToPublishDirectory="Never" />
		<Content Update="**\postcss.config.js" CopyToPublishDirectory="Never" />
	</ItemGroup>


</Project>
