<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PackageId>BlazorMHD.UI</PackageId>
    <Version>1.0.0</Version>
    <Authors>Your Name</Authors>
    <Description>Compact Blazor UI library for admin dashboards with Tailwind and dark mode.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Components\Navigation\Tabs\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Shared\Localiztion.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Localiztion.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Shared\Localiztion.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Localiztion.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
