// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using TaskResourceBlueprints.Entities.Questions.Assignments;
using TaskResourceBlueprints.Entities.Questions.Conditions;
using TaskResourceBlueprints.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class ConditionOptionRequirementMapper
{
    public static ConditionOptionRequirementDto ToDto(this OptionConditionRule e)
    {
        if (e == null) return null!;

        return new ConditionOptionRequirementDto
        {
            //ConditionId = e.ConditionId,
            //QuestionGroupId = e.QuestionGroupId,
            OptionItemId = e.OptionId
        };
    }
}