// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using TaskResourceBlueprints.Entities.Questions.Assignments;
using TaskResourceBlueprints.Entities.Questions.Conditions;
using TaskResourceBlueprints.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class OptionItemMapper
{
    public static OptionItemDto ToDto(this QuestionOptionDefinition e)
    {
        if (e == null) return null!;

        return new OptionItemDto
        {
            Id = e.Id,
            OptionGroupId = e.QuestionGroupId
        };
    }
}