// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class UnitGroupMapper
{
    public static UnitGroupDto ToDto(this TaskUnitGroup e)
    {
        if (e == null) return null!;

        return new UnitGroupDto
        {
            Id = e.Id,
            DisplayName = e.DisplayName
        };
    }
}