// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskResourceBlueprints.Infrastructure;

#nullable disable

namespace TaskResourceBlueprints.Migrations
{
    [DbContext(typeof(TaskResourceBlueprintsContext))]
    partial class TaskResourceBlueprintsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskDefinitionStateLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("TaskStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskStateId");

                    b.HasIndex("TaskDefinitionId", "TaskStateId")
                        .IsUnique();

                    b.ToTable("TaskDefinitionStateLinks");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TaskStateGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskStateGroupId");

                    b.HasIndex("TaskStateGroupId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskStates_Group_Name");

                    b.ToTable("TaskStates", t =>
                        {
                            t.HasCheckConstraint("CK_TaskStates_Name_NotEmpty", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_TaskStates_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskStateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskStateGroups_Name");

                    b.ToTable("TaskStateGroups", t =>
                        {
                            t.HasCheckConstraint("CK_TaskStateGroups_Name_NotEmpty", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_TaskStateGroups_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.ResourceDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ResType")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FolderId", "SortOrder", "Name");

                    b.HasIndex("IsActive", "IsVisible", "Name");

                    b.HasIndex("IsActive", "IsVisible", "Unit");

                    b.ToTable("Resources", t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Name_NotEmpty", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_Resources_Quantity_NonNegative", "[Quantity] IS NULL OR [Quantity] >= 0");

                            t.HasCheckConstraint("CK_Resources_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Resources.ResourceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId", "DisplayName")
                        .IsUnique()
                        .HasDatabaseName("UX_ResourceCategories_Parent_Name")
                        .HasFilter("[ParentCategoryId] IS NOT NULL");

                    b.HasIndex("ParentCategoryId", "SortOrder", "DisplayName");

                    b.ToTable("ResourceCategories", t =>
                        {
                            t.HasCheckConstraint("CK_ResourceCategories_Name_NotEmpty", "LEN(LTRIM(RTRIM([DisplayName]))) > 0");

                            t.HasCheckConstraint("CK_ResourceCategories_NoSelfParent", "[ParentCategoryId] IS NULL OR [ParentCategoryId] <> [Id]");

                            t.HasCheckConstraint("CK_ResourceCategories_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Resources.ResourceTenantLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<double?>("Co2")
                        .HasColumnType("float");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourceSortId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TenantId", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_ResourceTenantLink_Tenant_Resource");

                    b.ToTable("ResourceTenantLinks", t =>
                        {
                            t.HasCheckConstraint("CK_ResourceTenantLinks_Cost_NonNegative", "[Cost] IS NULL OR [Cost] >= 0");

                            t.HasCheckConstraint("CK_ResourceTenantLinks_Quantity_NonNegative", "[Quantity] IS NULL OR [Quantity] >= 0");

                            t.HasCheckConstraint("CK_ResourceTenantLinks_Resource_Positive", "[ResourceId] > 0");

                            t.HasCheckConstraint("CK_ResourceTenantLinks_Tenant_Positive", "[TenantId] > 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Tasks.TaskDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CapacityResourceId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChangeFactor1")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ChangeFactor2")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Code")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConversionParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HierarchyPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameSynonyms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedTextSv")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("PriceProduction")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Uncontrollable")
                        .HasColumnType("bit");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UnitSynonyms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<string>("VisibleFolderIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkloadThresholds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("HierarchyPath")
                        .HasDatabaseName("IX_Tasks_HierarchyPath");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tasks_Name");

                    b.HasIndex("NormalizedTextSv");

                    b.HasIndex("ParentCode");

                    b.HasIndex("Status", "SortOrder");

                    b.HasIndex("Status", "UsageCount", "Code");

                    b.ToTable("Tasks", t =>
                        {
                            t.HasCheckConstraint("CK_Tasks_ChangeFactors_Positive", "[ChangeFactor1] > 0 AND [ChangeFactor2] > 0");

                            t.HasCheckConstraint("CK_Tasks_Name_NotEmpty", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_Tasks_PriceProduction_NonNegative", "[PriceProduction] IS NULL OR [PriceProduction] >= 0");

                            t.HasCheckConstraint("CK_Tasks_Quantity_NonNegative", "[Quantity] IS NULL OR [Quantity] >= 0");

                            t.HasCheckConstraint("CK_Tasks_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Tasks.TaskDefinitionResourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddOns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ResourceDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ResourceId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Times")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceDefinitionId");

                    b.HasIndex("TaskDefinitionId", "ResourceDefinitionId")
                        .IsUnique();

                    b.ToTable("TaskDefinitionResourceLinks", t =>
                        {
                            t.HasCheckConstraint("CK_TaskDefinitionResourceLinks_Quantity_Positive", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_TaskDefinitionResourceLinks_Resource_Positive", "[ResourceId] > 0");

                            t.HasCheckConstraint("CK_TaskDefinitionResourceLinks_Task_Positive", "[TaskDefinitionId] > 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Tasks.TaskResourceSuggestionFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Feedback")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("SourceTaskId")
                        .HasColumnType("int");

                    b.Property<string>("SourceTaskName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("SourceTaskQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("SourceTaskUnit")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TargetTaskCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TargetTaskId")
                        .HasColumnType("int");

                    b.Property<string>("TargetTaskName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("TargetTaskQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TargetTaskUnit")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceTaskId", "Feedback");

                    b.HasIndex("TenantId", "ReviewStatus", "UpdatedAtUtc");

                    b.HasIndex("TenantId", "TargetTaskId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Feedback_Tenant_Task_Date");

                    b.HasIndex("TenantId", "TargetTaskId", "Source", "SourceTaskId")
                        .IsUnique();

                    b.ToTable("TaskResourceSuggestionFeedbacks", t =>
                        {
                            t.HasCheckConstraint("CK_TaskResourceSuggestionFeedbacks_Score_NonNegative", "[Score] >= 0");

                            t.HasCheckConstraint("CK_TaskResourceSuggestionFeedbacks_SourceQuantity_NonNegative", "[SourceTaskQuantity] IS NULL OR [SourceTaskQuantity] >= 0");

                            t.HasCheckConstraint("CK_TaskResourceSuggestionFeedbacks_SourceTask_Positive", "[SourceTaskId] > 0");

                            t.HasCheckConstraint("CK_TaskResourceSuggestionFeedbacks_TargetQuantity_NonNegative", "[TargetTaskQuantity] IS NULL OR [TargetTaskQuantity] >= 0");

                            t.HasCheckConstraint("CK_TaskResourceSuggestionFeedbacks_TargetTask_Positive", "[TargetTaskId] > 0");

                            t.HasCheckConstraint("CK_TaskResourceSuggestionFeedbacks_Tenant_Positive", "[TenantId] > 0");
                        });
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskDefinitionStateLink", b =>
                {
                    b.HasOne("TaskResourceBlueprints.Entities.Tasks.TaskDefinition", "Task")
                        .WithMany("StateLinks")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskResourceBlueprints.Entities.Lookups.TaskState", "State")
                        .WithMany("TaskLinks")
                        .HasForeignKey("TaskStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskState", b =>
                {
                    b.HasOne("TaskResourceBlueprints.Entities.Lookups.TaskStateGroup", "Group")
                        .WithMany("States")
                        .HasForeignKey("TaskStateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.ResourceDefinition", b =>
                {
                    b.HasOne("TaskResourceBlueprints.Entities.Resources.ResourceCategory", "Folder")
                        .WithMany("Resources")
                        .HasForeignKey("FolderId");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Resources.ResourceCategory", b =>
                {
                    b.HasOne("TaskResourceBlueprints.Entities.Resources.ResourceCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Resources.ResourceTenantLinkEntity", b =>
                {
                    b.HasOne("TaskResourceBlueprints.Entities.ResourceDefinition", null)
                        .WithMany("TenantLinks")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Tasks.TaskDefinitionResourceLink", b =>
                {
                    b.HasOne("TaskResourceBlueprints.Entities.ResourceDefinition", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskResourceBlueprints.Entities.Tasks.TaskDefinition", "Task")
                        .WithMany("ResourceLinks")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskState", b =>
                {
                    b.Navigation("TaskLinks");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Lookups.TaskStateGroup", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.ResourceDefinition", b =>
                {
                    b.Navigation("TenantLinks");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Resources.ResourceCategory", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TaskResourceBlueprints.Entities.Tasks.TaskDefinition", b =>
                {
                    b.Navigation("ResourceLinks");

                    b.Navigation("StateLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
