// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using ProjectImportHub.Entities;
using ProjectImportHub.Entities.Questions.Assignments;
using ProjectImportHub.Entities.Questions.Conditions;
using ProjectImportHub.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class ConditionVariableRequirementMapper
{
    public static ConditionVariableRequirementDto ToDto(this VariableConditionRule e)
    {
        if (e == null) return null!;

        return new ConditionVariableRequirementDto
        {
            Id = e.Id,
            QuestionConditionId = e.QuestionConditionId,
            VariableName = e.VariableName,
            MinAllowedValue = e.MinAllowedValue,
            MaxAllowedValue = e.MaxAllowedValue
        };
    }
}