// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using ProjectImportHub.Entities;
using ProjectImportHub.Entities.Questions.Assignments;
using ProjectImportHub.Entities.Questions.Conditions;
using ProjectImportHub.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class ConditionResourceRequirementMapper
{
    public static ConditionResourceRequirementDto ToDto(this ConditionResourceRequirementEntity e)
    {
        if (e == null) return null!;

        return new ConditionResourceRequirementDto
        {
            //Id = e.Id,
            //QuestionConditionId = e.QuestionConditionId,
            //ResourceOptionGroupId = e.ResourceOptionGroupId,
            ResourceOptionItemId = e.ResourceOptionItemId
        };
    }
}