// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using ProjectImportHub.Entities;
using ProjectImportHub.Entities.Questions.Assignments;
using ProjectImportHub.Entities.Questions.Conditions;
using ProjectImportHub.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class ConditionNumericRequirementMapper
{
    public static ConditionNumericRequirementDto ToDto(this NumericConditionRule e)
    {
        if (e == null) return null!;

        return new ConditionNumericRequirementDto
        {
            //Id = e.Id,
            //ConditionId = e.ConditionId,
            NumericInputId = e.NumericQuestionId,
            MaxAllowedValue = e.MaxAllowedValue,
            MinAllowedValue = e.MinAllowedValue
        };
    }
}