// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using TaskResourceBlueprints.Entities.Questions.Assignments;
using TaskResourceBlueprints.Entities.Questions.Conditions;
using TaskResourceBlueprints.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class NumericResourceAssignmentMapper
{
    public static NumericResourceAssignmentDto ToDto(this NumericResourceAssignment e)
    {
        if (e == null) return null!;

        return new NumericResourceAssignmentDto
        {
            //Id = e.Id,
            NumericId = e.NumericId,
            //AssignmentId = e.AssignmentId,
            MinInputValue = e.MinInputValue,
            MaxInputValue = e.MaxInputValue
        };
    }
}