// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using ProjectImportHub.Entities;
using ProjectImportHub.Entities.Questions.Assignments;
using ProjectImportHub.Entities.Questions.Conditions;
using ProjectImportHub.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class OptionResourceAssignmentMapper
{
    public static OptionResourceAssignmentDto ToDto(this OptionResourceAssignment e)
    {
        if (e == null) return null!;

        return new OptionResourceAssignmentDto
        {
            //Id = e.Id,
            ChoiceOptionId = e.OptionId,
            //AssignmentId = e.AssignmentId
        };
    }
}