// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using TaskResourceBlueprints.Entities.Questions.Assignments;
using TaskResourceBlueprints.Entities.Questions.Conditions;
using TaskResourceBlueprints.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class OptionGroupMapper
{
    public static OptionGroupDto ToDto(this QuestionGroupDefinition e)
    {
        if (e == null) return null!;

        return new OptionGroupDto
        {
            Id = e.Id,
            SectionKey = e.SectionKey,
            TaskId = e.TaskId
        };
    }
}