// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using TaskResourceBlueprints.Entities.Questions.Assignments;
using TaskResourceBlueprints.Entities.Questions.Conditions;
using TaskResourceBlueprints.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;
using TaskResourceBlueprints.Entities.Resources;

namespace ProjectManagement.Shared.Mappers;

public static class ResourceFolderMapper
{
    public static ResourceFolderDto ToDto(this ResourceCategory e)
    {
        if (e == null) return null!;

        return new ResourceFolderDto
        {
            Id = e.Id,
            DisplayName = e.DisplayName,
            Note = e.Note,
            SortOrder = e.SortOrder,
            ParentFolder = e.ParentCategory?.ToDto(),
            ParentFolderId = e.ParentCategoryId
        };
    }
}