// <auto-generated> Static mappers from Entities to DTOs. </auto-generated>
using System.Linq;
using TaskResourceBlueprints.Entities;
using TaskResourceBlueprints.Entities.Questions.Assignments;
using TaskResourceBlueprints.Entities.Questions.Conditions;
using TaskResourceBlueprints.Entities.Questions.Groups;
using ProjectManagement.Shared.DTO.ProjectAppStorage;

namespace ProjectManagement.Shared.Mappers;

public static class TaskConditionMapper
{
    public static TaskConditionDto ToDto(this ConditionDefinition e)
    {
        if (e == null) return null!;

        return new TaskConditionDto
        {
            Id = e.Id,
        };
    }
}