<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-ProjectManagement_Adminstrator-0220d739-c448-4463-be45-9d5f7a58a47d</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <PropertyGroup>
    <SatelliteResourceLanguages>en;sv</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**\node_modules\**" />
    <Content Remove="**\node_modules\**" />
    <EmbeddedResource Remove="**\node_modules\**" />
    <None Remove="**\node_modules\**" />
  </ItemGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\node_modules\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ContextMenuMHD" Version="1.4.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NCalcSync" Version="5.12.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthPermissions\AuthPermissions.csproj" />
    <ProjectReference Include="..\TaskResourceBlueprints\TaskResourceBlueprints.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
    <ProjectReference Include="D:\Library\3\BlazorMHD\BlazorMHD.UI\BlazorMHD.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="**\package.json" CopyToPublishDirectory="Never" />
    <Content Update="**\package-lock.json" CopyToPublishDirectory="Never" />
    <Content Update="**\tailwind.config.js" CopyToPublishDirectory="Never" />
    <Content Update="**\postcss.config.js" CopyToPublishDirectory="Never" />
  </ItemGroup>



</Project>
