// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class NumericResourceAssignmentDto
{
    //public int Id { get; set; }
    public int NumericId { get; set; }
    //public int ResourceAssignmentId { get; set; }
    public double? MinInputValue { get; set; }
    public double? MaxInputValue { get; set; }
    public List<string> Formulas { get; set; } = [];
}