// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class NumericResourceAssignmentDto
{
    public int NumericId { get; set; }
    public decimal? MinInputValue { get; set; }
    public decimal? MaxInputValue { get; set; }
    public List<string> Formulas { get; set; } = [];
}