// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class OptionResourceAssignmentDto
{
    //public int Id { get; set; }
    public int ChoiceOptionId { get; set; }
    //public int ResourceAssignmentId { get; set; }
    public List<string> Formulas { get; set; } = [];
}