// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using ProjectManagement.Shared.Base.AppTenant;
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ResourceAssignmentDto
{
    public List<RoleDTO> CapRole { get; set; } = [];
    public List<string> Formulas { get; set; } = [];
    public ResourceDto Resource { get; set; } = null!;
    public int QuestionConditionId { get; set; }

    public List<NumericResourceAssignmentDto> NumericResourceFormulas { get; set; } = [];
    public List<OptionResourceAssignmentDto> OptionResourceFormulas { get; set; } = [];
}