// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using ProjectManagement.Shared.Base.AppTenant;
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class TaskResourceAssignmentDto
{
    public int Id { get; set; }
    public bool IsActive { get; set; } = true;
    public double ChangeFactor1 { get; set; } = 1;
    public double ChangeFactor2 { get; set; } = 1;
    public double CapWaste { get; set; } = 1;
    public double? BaseCost { get; set; } = 0;
    public bool Uncontrollable { get; set; } = false;
    public List<RoleDTO> CapRole { get; set; } = [];
    public List<string> Formulas { get; set; } = [];
    public int TaskId { get; set; }
    public ProjectTaskDto Task { get; set; }
    public int ResourceId { get; set; }
    public ResourceDto Resource { get; set; }

    public double? CalcCap()
    {
        double? q = Resource.Data.Quantity;
        if(CapRole != null && q.HasValue)
        foreach (var item in CapRole)
        {
            if (item.Min <= q && item.Max >= q) return item.Value;
        }
        return q;
    }
}