// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using ProjectManagement.Shared.Base.AppTenant;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class TaskResourceAssignmentDto
{
    public int Id { get; set; }
    public bool IsActive { get; set; } = true;
    public double ChangeFactor1 { get; set; } = 1;
    public double ChangeFactor2 { get; set; } = 1;
    public double CapWaste { get; set; } = 1;
    public double? BaseCost { get; set; } = 0;
    public bool Uncontrollable { get; set; } = false;
    public List<RoleDTO> CapRole { get; set; } = [];
    public List<string> Formulas { get; set; } = [];
    public int TaskId { get; set; }
    public ProjectTaskDto Task { get; set; } = null!;
    public int ResourceId { get; set; }
    public ResourceDto Resource { get; set; } = null!;

    public double? CalcCap()
    {
        decimal? q = Resource.Data.Quantity;
        if (q.HasValue)
        foreach (var item in CapRole)
        {
            if ((double)q.Value >= item.Min && (double)q.Value <= item.Max) return item.Value;
        }
        return q.HasValue ? (double)q.Value : null;
    }
}
