// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class FallDto
{
    public int Id { get; set; }
    public string? DisplayName { get; set; }
    public int SortOrder { get; set; }
    public bool IsVisible { get; set; } = true;
}