// <auto-generated> Generated from Entities for DTO usage. </auto-generated>

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public enum DataType
{
    Text = 0,
    Number = 1
}
public class ResourcePropertyBindDto
{
    public int Id { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public bool IsUserEditable { get; set; } = true;
    public DataType DataType { get; set; } = DataType.Text;
    public double? MaxNumericValue { get; set; }
    public string TextDefault { get; set; }
    public double? NumberDefault { get; set; }
}