// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using ProjectManagement.Shared.DTO.Calculation;
using ProjectManagement.Shared.DTO.ProjectAppStorage.Service;
using ProjectManagement.Shared.Helper.ProjectAppStorage;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ResourceTenantLinkBase
{
    public string Name { get; set; } = string.Empty;
    public int? StatusId { get; set; }
    public int? ResourceTypeId { get; set; }
    public int? ResourceSortId { get; set; }
    public int? AccountId { get; set; }

    public double? Co2 { get; set; } // خليها double عادي

    // كانت double -> صارت decimal
    public decimal? Cost { get; set; }
    public decimal? Quantity { get; set; }
}

public class ProjectTaskDto
{
    public bool Uncontrollable { get; set; }

    public int Id { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public int SortOrder { get; set; }
    public bool IsVisible { get; set; } = true;
    public string Note { get; set; } = string.Empty;
    public List<string> UpperNote { get; set; } = [];

    // كانت double -> صارت decimal
    public decimal? Quantity { get; set; }

    public string UnitCode { get; set; } = string.Empty;
    public string Code { get; set; } = string.Empty;

    // كانت double -> صارت decimal
    public decimal ChangeFactor1 { get; set; } = 1;
    public decimal ChangeFactor2 { get; set; } = 1;

    public bool IsActive { get; set; } = true;
    public int? UnitGroupId { get; set; }
    public int? CapacityResourceId { get; set; }

    public UnitGroupDto UnitGroup { get; set; } = new();

    // إذا تستخدمها للـ thresholds (UI فقط) تقدر تتركها double،
    // لكن الأفضل توحيدها:
    public List<decimal> WorkloadThresholds { get; set; } = [0, 0, 0];

    [NotMapped] public Dictionary<ParamName, decimal> ParameterValues { get; } = [];
    [NotMapped] public string NewUnitCode { get; set; } = string.Empty;

    public List<ResourceDto> BaseResources { get; set; } = [];
    public List<ResourceDto> ResultResources { get; set; } = [];

    public List<OptionGroupDto> OptionGroups { get; set; } = [];
    public List<ResourceOptionGroupDto> ResourceOptionGroups { get; set; } = [];
    public List<NumericInputDto> NumericInputs { get; set; } = [];
    public List<TaskConditionDto> Conditions { get; set; } = [];

    [JsonIgnore] public bool Collspanded { get; set; }
    [JsonIgnore] public bool IsLoading { get; set; }
    [JsonIgnore] public bool Added { get; set; }
    [JsonIgnore] public int StatusId { get; set; }

    [JsonIgnore] public List<ResourceDto> Resources => BaseResources.Concat(ResultResources).ToList();

    // كانت double -> صارت decimal
    [JsonIgnore] public decimal TotalCost => Resources.Where(x => x.Id > 0).Sum(x => x.TotalCost);
}