// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class UnitGroupDto
{
    public int Id { get; set; }
    public string? DisplayName { get; set; }
    public List<string> Keys { get; set; } = [];

}