// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class UnitGroupDto
{
    public int Id { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public List<string> Keys { get; set; } = [];

}
