// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class NumericInputDto
{
    public int Id { get; set; }
    public string DisplayName { get; set; } = string.Empty;

    public double? MinInputValue { get; set; }
    public double? MaxInputValue { get; set; }
    public string SectionKey { get; set; } = string.Empty;
    public int SortOrder { get; set; } = 0;
}
