// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class OptionItemDto
{
    public int Id { get; set; }
    public string DisplayName { get; set; } = string.Empty;
    public int SortOrder { get; set; }

    public int OptionGroupId { get; set; }
    public List<string> RevealedSectionKeys { get; set; } = [];

}