// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using ProjectManagement.Shared.Base.ProjectAppStorage;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class OptionGroupDto
{
    public int Id { get; set; }
    public string SectionKey { get; set; } = string.Empty;
    public int TaskId { get; set; }
    public int SortOrder { get; set; } = 0;
    public string DisplayName { get; set; } = string.Empty;
    public SelectionMode SelectionMode { get; set; } = SelectionMode.Multiple;

    public List<OptionItemDto> Options { get; set; } = [];
}
