// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ResourceOptionItemDto
{
    public int Id { get; set; }
    //public int ResourceChoiceGroupId { get; set; }
    public string ResourceName { get; set; } = string.Empty;
    public int SortOrder { get; set; }

    //public ResourceDto Resource { get; set; } = null!;
    //public int ResourceId { get; set; }
}
