// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
using System.Collections.Generic;

namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ResourceOptionGroupDto
{
    public int Id { get; set; }
    public string SectionKey { get; set; }
    public int SortOrder { get; set; } = 0;
    public string DisplayName { get; set; } = string.Empty;

    public List<ResourceOptionItemDto> Items { get; set; } = [];
}