//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Adminstrator.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagement.Adminstrator.Shared.ResourceFiles.ResourceLoc", typeof(ResourceLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main category.
        /// </summary>
        public static string baseCategory {
            get {
                return ResourceManager.GetString("baseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Company.
        /// </summary>
        public static string ByCompany {
            get {
                return ResourceManager.GetString("ByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Resources.
        /// </summary>
        public static string ByResource {
            get {
                return ResourceManager.GetString("ByResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client project manager.
        /// </summary>
        public static string clientsProjectmanager {
            get {
                return ResourceManager.GetString("clientsProjectmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collective Labour Agreement.
        /// </summary>
        public static string collectiveLabourAgreement {
            get {
                return ResourceManager.GetString("collectiveLabourAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of invoice control.
        /// </summary>
        public static string dateInvoiceControl {
            get {
                return ResourceManager.GetString("dateInvoiceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of control.
        /// </summary>
        public static string dateOfControl {
            get {
                return ResourceManager.GetString("dateOfControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string designer {
            get {
                return ResourceManager.GetString("designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Power.
        /// </summary>
        public static string ElectricalPower {
            get {
                return ResourceManager.GetString("ElectricalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string income {
            get {
                return ResourceManager.GetString("income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Infrastructure {
            get {
                return ResourceManager.GetString("Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Percent.
        /// </summary>
        public static string inprecent {
            get {
                return ResourceManager.GetString("inprecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Verification Date.
        /// </summary>
        public static string InvoiceVerificationDate {
            get {
                return ResourceManager.GetString("InvoiceVerificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines and equipments.
        /// </summary>
        public static string MachinesAndEquipments {
            get {
                return ResourceManager.GetString("MachinesAndEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string maps {
            get {
                return ResourceManager.GetString("maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string offer {
            get {
                return ResourceManager.GetString("offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only IsActive.
        /// </summary>
        public static string onlyActive {
            get {
                return ResourceManager.GetString("onlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities/risks.
        /// </summary>
        public static string opportunitiesRisks {
            get {
                return ResourceManager.GetString("opportunitiesRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overhead costs.
        /// </summary>
        public static string overheadCosts {
            get {
                return ResourceManager.GetString("overheadCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability %.
        /// </summary>
        public static string probability {
            get {
                return ResourceManager.GetString("probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best case.
        /// </summary>
        public static string probabilityBest {
            get {
                return ResourceManager.GetString("probabilityBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability value.
        /// </summary>
        public static string probabilityValue {
            get {
                return ResourceManager.GetString("probabilityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst case.
        /// </summary>
        public static string probabilityWorth {
            get {
                return ResourceManager.GetString("probabilityWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects overhead costs.
        /// </summary>
        public static string ProjectOverheadCosts {
            get {
                return ResourceManager.GetString("ProjectOverheadCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string resource {
            get {
                return ResourceManager.GetString("resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to the cloud.
        /// </summary>
        public static string saveCloud {
            get {
                return ResourceManager.GetString("saveCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self inspection.
        /// </summary>
        public static string selfInspection {
            get {
                return ResourceManager.GetString("selfInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up a conversion set.
        /// </summary>
        public static string Setting_up_a_conversion_set {
            get {
                return ResourceManager.GetString("Setting up a conversion set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcontractors.
        /// </summary>
        public static string Subcontractors {
            get {
                return ResourceManager.GetString("Subcontractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub ParentTask.
        /// </summary>
        public static string SubTask {
            get {
                return ResourceManager.GetString("SubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary sheet.
        /// </summary>
        public static string summarySheet {
            get {
                return ResourceManager.GetString("summarySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentTask.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentTask status.
        /// </summary>
        public static string taskStatus {
            get {
                return ResourceManager.GetString("taskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenders.
        /// </summary>
        public static string tender {
            get {
                return ResourceManager.GetString("tender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VVS.
        /// </summary>
        public static string VVS {
            get {
                return ResourceManager.GetString("VVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        public static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
