// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectImportHub.Infrastructure;

#nullable disable

namespace ProjectImportHub.Migrations
{
    [DbContext(typeof(ProjectImportHubContext))]
    [Migration("20251114131235_DB251108_5")]
    partial class DB251108_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectImportHub.Entities.ActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ActionTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Assignments.ResourcePropertyBindEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("NumberDefault")
                        .HasColumnType("float");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("TextDefault")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceProperty");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Assignments.ResourceTenantLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<double?>("Co2")
                        .HasColumnType("float");

                    b.Property<double?>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourceSortId")
                        .HasColumnType("int");

                    b.Property<int?>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "ResourceId" }, "IX_ResourceTenantLink_Tenant_Resource");

                    b.HasIndex(new[] { "ResourceId", "TenantId" }, "UX_ResourceTenantLink_Resource_Tenant")
                        .IsUnique();

                    b.ToTable("ResourceTenant");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.FallEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Falls");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ProjectTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int");

                    b.Property<int?>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CapacityResourceId")
                        .HasColumnType("int");

                    b.Property<double>("ChangeFactor1")
                        .HasColumnType("float");

                    b.Property<double>("ChangeFactor2")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FallId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("HeaderNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("Uncontrollable")
                        .HasColumnType("bit");

                    b.Property<string>("UnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitGroupId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("UpperNote")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("VisibleFolderIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("WorkloadThresholds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("FallId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UnitGroupId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.NumericResourceAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Formulas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxInputValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinInputValue")
                        .HasColumnType("float");

                    b.Property<int>("NumericId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceAssignmentId");

                    b.HasIndex("NumericId", "ResourceAssignmentId")
                        .IsUnique();

                    b.ToTable("NumericGroupResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.OptionResourceAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoiceOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Formulas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceAssignmentId");

                    b.HasIndex("ChoiceOptionId", "ResourceAssignmentId")
                        .IsUnique();

                    b.ToTable("OptionResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.ResourceAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BaseCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("float(18)");

                    b.Property<string>("CapRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CapWaste")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<double>("ChangeFactor1")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<double>("ChangeFactor2")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.PrimitiveCollection<string>("Formulas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionConditionId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<bool>("Uncontrollable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuestionConditionId");

                    b.HasIndex("ResourceId");

                    b.ToTable("ConditionResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.TaskResourceAssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BaseCost")
                        .HasColumnType("float");

                    b.Property<string>("CapRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CapWaste")
                        .HasColumnType("float");

                    b.Property<double>("ChangeFactor1")
                        .HasColumnType("float");

                    b.Property<double>("ChangeFactor2")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("Formulas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<bool>("Uncontrollable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionNumericRequirementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DefaultValue")
                        .HasColumnType("float");

                    b.Property<double?>("MaxAllowedValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinAllowedValue")
                        .HasColumnType("float");

                    b.Property<int>("NumericInputId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionConditionId")
                        .HasColumnType("int");

                    b.Property<int>("SetKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumericInputId");

                    b.HasIndex("QuestionConditionId", "SetKey");

                    b.ToTable("NumericRequirements");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionOptionRequirementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.Property<int>("OptionItemId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionConditionId")
                        .HasColumnType("int");

                    b.Property<int>("SetKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId");

                    b.HasIndex("OptionItemId");

                    b.HasIndex("QuestionConditionId", "OptionGroupId", "OptionItemId", "SetKey")
                        .IsUnique();

                    b.ToTable("ChoiceRequirements");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionResourceRequirementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionConditionId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceOptionGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceOptionItemId")
                        .HasColumnType("int");

                    b.Property<int>("SetKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceOptionGroupId");

                    b.HasIndex("ResourceOptionItemId");

                    b.HasIndex("QuestionConditionId", "ResourceOptionGroupId", "ResourceOptionItemId", "SetKey")
                        .IsUnique();

                    b.ToTable("ResourceRequirements");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionVariableRequirementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("MaxAllowedValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinAllowedValue")
                        .HasColumnType("float");

                    b.Property<int>("QuestionConditionId")
                        .HasColumnType("int");

                    b.Property<int>("SetKey")
                        .HasColumnType("int");

                    b.Property<string>("VariableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionConditionId");

                    b.ToTable("ConditionVariableRequirement");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultOptionRequirementId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultResourceRequirementId")
                        .HasColumnType("int");

                    b.Property<int>("NumericToResourceLogic")
                        .HasColumnType("int");

                    b.Property<int>("OptionToNumericLogic")
                        .HasColumnType("int");

                    b.Property<int>("OptionToResourceLogic")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultOptionRequirementId");

                    b.HasIndex("DefaultResourceRequirementId");

                    b.HasIndex("TaskId");

                    b.ToTable("QuestionConditions");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.NumericInputEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("MaxInputValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinInputValue")
                        .HasColumnType("float");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "SortOrder");

                    b.HasIndex("TaskId", "SectionKey", "SortOrder");

                    b.ToTable("NumericInputGroups");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.OptionGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SelectionMode")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "SortOrder");

                    b.HasIndex("TaskId", "SectionKey", "SortOrder");

                    b.ToTable("OptionGroups");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.OptionItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.Property<string>("RevealedSectionKeys")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId");

                    b.ToTable("OptionItems");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.ResourceOptionGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "SortOrder");

                    b.HasIndex("TaskId", "SectionKey", "SortOrder");

                    b.ToTable("ResourceOptionGroups");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.ResourceOptionItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourceChoiceGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ResourceChoiceGroupId", "ResourceId");

                    b.ToTable("ResourceOptionItems");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalcResCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResType")
                        .HasColumnType("int");

                    b.Property<double>("SortOrder")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourceFolderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourcePropertyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<double?>("DefaultNumericValue")
                        .HasColumnType("float");

                    b.Property<string>("DefaultTextValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUserEditable")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxNumericValue")
                        .HasColumnType("float");

                    b.Property<int>("PropertySetId")
                        .HasColumnType("int");

                    b.Property<double?>("PropertyValues")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PropertySetId");

                    b.ToTable("ResourceProperties");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourcePropertySetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourcePropertySets");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.UnitGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Keys")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitGroups");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Assignments.ResourcePropertyBindEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ResourcePropertyEntity", "Property")
                        .WithMany("PropertiesBind")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.ResourceEntity", "Resource")
                        .WithMany("PropertiesBind")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Assignments.ResourceTenantLinkEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ResourceEntity", "Resource")
                        .WithMany("ResourcesTenant")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ProjectTaskEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ActionEntity", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId");

                    b.HasOne("ProjectImportHub.Entities.ActionTypeEntity", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId");

                    b.HasOne("ProjectImportHub.Entities.FallEntity", "Fall")
                        .WithMany()
                        .HasForeignKey("FallId");

                    b.HasOne("ProjectImportHub.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("ProjectImportHub.Entities.UnitGroupEntity", "UnitGroup")
                        .WithMany("Tasks")
                        .HasForeignKey("UnitGroupId");

                    b.Navigation("Action");

                    b.Navigation("ActionType");

                    b.Navigation("Fall");

                    b.Navigation("Location");

                    b.Navigation("UnitGroup");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.NumericResourceAssignmentEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.NumericInputEntity", "Numeric")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("NumericId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Assignments.ResourceAssignmentEntity", "ResourceAssignment")
                        .WithMany("NumericResourceFormulas")
                        .HasForeignKey("ResourceAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Numeric");

                    b.Navigation("ResourceAssignment");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.OptionResourceAssignmentEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.OptionItemEntity", "ChoiceOption")
                        .WithMany("OptionResourceAssignments")
                        .HasForeignKey("ChoiceOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Assignments.ResourceAssignmentEntity", "ResourceAssignment")
                        .WithMany("OptionResourceFormulas")
                        .HasForeignKey("ResourceAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChoiceOption");

                    b.Navigation("ResourceAssignment");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.ResourceAssignmentEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", "QuestionCondition")
                        .WithMany("ConditionResourceAssignments")
                        .HasForeignKey("QuestionConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionCondition");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.TaskResourceAssignmentEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.ProjectTaskEntity", "Task")
                        .WithMany("TaskResourceAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionNumericRequirementEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.NumericInputEntity", "NumericInput")
                        .WithMany()
                        .HasForeignKey("NumericInputId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", "QuestionCondition")
                        .WithMany("NumericRequirements")
                        .HasForeignKey("QuestionConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumericInput");

                    b.Navigation("QuestionCondition");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionOptionRequirementEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.OptionGroupEntity", "OptionGroup")
                        .WithMany()
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.OptionItemEntity", "OptionItem")
                        .WithMany()
                        .HasForeignKey("OptionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", "QuestionCondition")
                        .WithMany("OptionRequirements")
                        .HasForeignKey("QuestionConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionGroup");

                    b.Navigation("OptionItem");

                    b.Navigation("QuestionCondition");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionResourceRequirementEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", "QuestionCondition")
                        .WithMany("ResourceRequirements")
                        .HasForeignKey("QuestionConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.ResourceOptionGroupEntity", "ResourceOptionGroup")
                        .WithMany()
                        .HasForeignKey("ResourceOptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.ResourceOptionItemEntity", "ResourceOptionItem")
                        .WithMany()
                        .HasForeignKey("ResourceOptionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionCondition");

                    b.Navigation("ResourceOptionGroup");

                    b.Navigation("ResourceOptionItem");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.ConditionVariableRequirementEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", "QuestionCondition")
                        .WithMany("VariableRequirements")
                        .HasForeignKey("QuestionConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionCondition");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.ConditionOptionRequirementEntity", "DefaultOptionRequirement")
                        .WithMany()
                        .HasForeignKey("DefaultOptionRequirementId");

                    b.HasOne("ProjectImportHub.Entities.Questions.Conditions.ConditionResourceRequirementEntity", "DefaultResourceRequirement")
                        .WithMany()
                        .HasForeignKey("DefaultResourceRequirementId");

                    b.HasOne("ProjectImportHub.Entities.ProjectTaskEntity", "Task")
                        .WithMany("Conditions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultOptionRequirement");

                    b.Navigation("DefaultResourceRequirement");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.NumericInputEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ProjectTaskEntity", "Task")
                        .WithMany("NumericInputs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.OptionGroupEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ProjectTaskEntity", "Task")
                        .WithMany("OptionGroups")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.OptionItemEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.OptionGroupEntity", "OptionGroup")
                        .WithMany("Options")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.ResourceOptionGroupEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ProjectTaskEntity", "Task")
                        .WithMany("ResourceOptionGroups")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.ResourceOptionItemEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.Questions.Groups.ResourceOptionGroupEntity", "ResourceOptionGroup")
                        .WithMany("Items")
                        .HasForeignKey("ResourceChoiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectImportHub.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("ResourceOptionGroup");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourceEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ResourceFolderEntity", "Folder")
                        .WithMany("Resources")
                        .HasForeignKey("FolderId");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourceFolderEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ResourceFolderEntity", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourcePropertyEntity", b =>
                {
                    b.HasOne("ProjectImportHub.Entities.ResourcePropertySetEntity", "PropertySet")
                        .WithMany("Properties")
                        .HasForeignKey("PropertySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertySet");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ProjectTaskEntity", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("NumericInputs");

                    b.Navigation("OptionGroups");

                    b.Navigation("ResourceOptionGroups");

                    b.Navigation("TaskResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Assignments.ResourceAssignmentEntity", b =>
                {
                    b.Navigation("NumericResourceFormulas");

                    b.Navigation("OptionResourceFormulas");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Conditions.TaskConditionEntity", b =>
                {
                    b.Navigation("ConditionResourceAssignments");

                    b.Navigation("NumericRequirements");

                    b.Navigation("OptionRequirements");

                    b.Navigation("ResourceRequirements");

                    b.Navigation("VariableRequirements");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.NumericInputEntity", b =>
                {
                    b.Navigation("ResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.OptionGroupEntity", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.OptionItemEntity", b =>
                {
                    b.Navigation("OptionResourceAssignments");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.Questions.Groups.ResourceOptionGroupEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourceEntity", b =>
                {
                    b.Navigation("PropertiesBind");

                    b.Navigation("ResourcesTenant");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourceFolderEntity", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourcePropertyEntity", b =>
                {
                    b.Navigation("PropertiesBind");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.ResourcePropertySetEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ProjectImportHub.Entities.UnitGroupEntity", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
