//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Client.Shared.ResourceFiles.Calculation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalcResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalcResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagement.Client.Shared.ResourceFiles.Calculation.CalcResource", typeof(CalcResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account groups.
        /// </summary>
        public static string accountGroups {
            get {
                return ResourceManager.GetString("accountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actually quantity.
        /// </summary>
        public static string actuallyQuantity {
            get {
                return ResourceManager.GetString("actuallyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Cost.
        /// </summary>
        public static string baseCost {
            get {
                return ResourceManager.GetString("baseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string calculation {
            get {
                return ResourceManager.GetString("calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap.
        /// </summary>
        public static string cap {
            get {
                return ResourceManager.GetString("cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling Price.
        /// </summary>
        public static string ceilingPrice {
            get {
                return ResourceManager.GetString("ceilingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity-driving factor.
        /// </summary>
        public static string changeFactor1 {
            get {
                return ResourceManager.GetString("changeFactor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity conversion factor.
        /// </summary>
        public static string changeFactor2 {
            get {
                return ResourceManager.GetString("changeFactor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit conversion factor.
        /// </summary>
        public static string changeFactor2Resource {
            get {
                return ResourceManager.GetString("changeFactor2Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co2/ unit.
        /// </summary>
        public static string co2 {
            get {
                return ResourceManager.GetString("co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost/ unit.
        /// </summary>
        public static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Date.
        /// </summary>
        public static string decisionDate {
            get {
                return ResourceManager.GetString("decisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string diff {
            get {
                return ResourceManager.GetString("diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net earnings.
        /// </summary>
        public static string earning {
            get {
                return ResourceManager.GetString("earning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV.
        /// </summary>
        public static string ev {
            get {
                return ResourceManager.GetString("ev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string factor {
            get {
                return ResourceManager.GetString("factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Q.
        /// </summary>
        public static string fixedQ {
            get {
                return ResourceManager.GetString("fixedQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly price List.
        /// </summary>
        public static string hourlyPriceList {
            get {
                return ResourceManager.GetString("hourlyPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        public static string inspector {
            get {
                return ResourceManager.GetString("inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key Value.
        /// </summary>
        public static string keyValue {
            get {
                return ResourceManager.GetString("keyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV.
        /// </summary>
        public static string kv {
            get {
                return ResourceManager.GetString("kv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market prices.
        /// </summary>
        public static string MarketPrices {
            get {
                return ResourceManager.GetString("MarketPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price.
        /// </summary>
        public static string minPrice {
            get {
                return ResourceManager.GetString("minPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net cal..
        /// </summary>
        public static string netCal {
            get {
                return ResourceManager.GetString("netCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetCal OH.
        /// </summary>
        public static string netCalOH {
            get {
                return ResourceManager.GetString("netCalOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net cost/ unit.
        /// </summary>
        public static string netCostQ {
            get {
                return ResourceManager.GetString("netCostQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New unit.
        /// </summary>
        public static string newUnit {
            get {
                return ResourceManager.GetString("newUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        public static string opportunity {
            get {
                return ResourceManager.GetString("opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhead costs.
        /// </summary>
        public static string overheadCosts {
            get {
                return ResourceManager.GetString("overheadCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview information about the project.
        /// </summary>
        public static string overviewInfoProject {
            get {
                return ResourceManager.GetString("overviewInfoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/ unit.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price actually quantity.
        /// </summary>
        public static string priceActuallyQuantity {
            get {
                return ResourceManager.GetString("priceActuallyQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price actually quantity tax.
        /// </summary>
        public static string priceActuallyQuantityTax {
            get {
                return ResourceManager.GetString("priceActuallyQuantityTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price OG.
        /// </summary>
        public static string priceOG {
            get {
                return ResourceManager.GetString("priceOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price production.
        /// </summary>
        public static string priceProduction {
            get {
                return ResourceManager.GetString("priceProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price unit.
        /// </summary>
        public static string priceQ {
            get {
                return ResourceManager.GetString("priceQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price/ unit Tax.
        /// </summary>
        public static string priceQTax {
            get {
                return ResourceManager.GetString("priceQTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price sub..
        /// </summary>
        public static string priceSub {
            get {
                return ResourceManager.GetString("priceSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price sub tax.
        /// </summary>
        public static string priceSubTax {
            get {
                return ResourceManager.GetString("priceSubTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Totally Tax.
        /// </summary>
        public static string priceTotallyTax {
            get {
                return ResourceManager.GetString("priceTotallyTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Total Sub.
        /// </summary>
        public static string priceTotalSub {
            get {
                return ResourceManager.GetString("priceTotalSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price total Sub tax.
        /// </summary>
        public static string priceTotalSubTax {
            get {
                return ResourceManager.GetString("priceTotalSubTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Totally.
        /// </summary>
        public static string priceTotaly {
            get {
                return ResourceManager.GetString("priceTotaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price worked/ unit.
        /// </summary>
        public static string priceWorkedQ {
            get {
                return ResourceManager.GetString("priceWorkedQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price worked/ unit tax.
        /// </summary>
        public static string priceWorkedQTax {
            get {
                return ResourceManager.GetString("priceWorkedQTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win probability.
        /// </summary>
        public static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        public static string procurement {
            get {
                return ResourceManager.GetString("procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement methods.
        /// </summary>
        public static string procurementMethods {
            get {
                return ResourceManager.GetString("procurementMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project compensation.
        /// </summary>
        public static string projectCompensation {
            get {
                return ResourceManager.GetString("projectCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project contract.
        /// </summary>
        public static string projectContract {
            get {
                return ResourceManager.GetString("projectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type.
        /// </summary>
        public static string projectType {
            get {
                return ResourceManager.GetString("projectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Date.
        /// </summary>
        public static string publicationDate {
            get {
                return ResourceManager.GetString("publicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource sort.
        /// </summary>
        public static string resourceSort {
            get {
                return ResourceManager.GetString("resourceSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources status.
        /// </summary>
        public static string resourcesStatus {
            get {
                return ResourceManager.GetString("resourcesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type.
        /// </summary>
        public static string resourceType {
            get {
                return ResourceManager.GetString("resourceType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource type system.
        /// </summary>
        public static string resourceTypeSystem {
            get {
                return ResourceManager.GetString("resourceTypeSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string badgeSystem {
            get {
                return ResourceManager.GetString("badgeSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string badgeCompany {
            get {
                return ResourceManager.GetString("badgeCompany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter tasks...
        /// </summary>
        public static string filterTasks {
            get {
                return ResourceManager.GetString("filterTasks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter suggestions...
        /// </summary>
        public static string filterSuggestions {
            get {
                return ResourceManager.GetString("filterSuggestions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min score.
        /// </summary>
        public static string minScore {
            get {
                return ResourceManager.GetString("minScore", resourceCulture);
            }
        }

        public static string parentContext => ResourceManager.GetString("parentContext", resourceCulture)!;
        public static string capTask       => ResourceManager.GetString("capTask", resourceCulture)!;
        public static string feedbackLabel   => ResourceManager.GetString("feedbackLabel", resourceCulture)!;
        public static string feedbackGood    => ResourceManager.GetString("feedbackGood", resourceCulture)!;
        public static string feedbackBad     => ResourceManager.GetString("feedbackBad", resourceCulture)!;
        public static string feedbackUnit    => ResourceManager.GetString("feedbackUnit", resourceCulture)!;
        public static string feedbackMissing => ResourceManager.GetString("feedbackMissing", resourceCulture)!;
        public static string feedbackType    => ResourceManager.GetString("feedbackType", resourceCulture)!;
        public static string feedbackSave    => ResourceManager.GetString("feedbackSave", resourceCulture)!;
        public static string suggestionLeafOnly              => ResourceManager.GetString("suggestionLeafOnly", resourceCulture)!;
        public static string suggestionBothDisabled          => ResourceManager.GetString("suggestionBothDisabled", resourceCulture)!;
        public static string suggestionNoTasksAtScore        => ResourceManager.GetString("suggestionNoTasksAtScore", resourceCulture)!;
        public static string suggestionNoTasksAboveThreshold => ResourceManager.GetString("suggestionNoTasksAboveThreshold", resourceCulture)!;
        public static string suggestionFilterHidden          => ResourceManager.GetString("suggestionFilterHidden", resourceCulture)!;
        public static string suggestionNoLeafTasks           => ResourceManager.GetString("suggestionNoLeafTasks", resourceCulture)!;
        public static string suggestionMissingCount          => ResourceManager.GetString("suggestionMissingCount", resourceCulture)!;
        public static string suggestionFilterNoMatch         => ResourceManager.GetString("suggestionFilterNoMatch", resourceCulture)!;
        public static string suggestionFilterBelowScore     => ResourceManager.GetString("suggestionFilterBelowScore", resourceCulture)!;
        public static string quickAdd                        => ResourceManager.GetString("quickAdd", resourceCulture)!;

        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string responsible {
            get {
                return ResourceManager.GetString("responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string risk {
            get {
                return ResourceManager.GetString("risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string StorageSort {
            get {
                return ResourceManager.GetString("StorageSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected.
        /// </summary>
        public static string suggestionAddSelected {
            get {
                return ResourceManager.GetString("suggestionAddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource suggestions were found for this task..
        /// </summary>
        public static string suggestionNoResults {
            get {
                return ResourceManager.GetString("suggestionNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string suggestionShowMore {
            get {
                return ResourceManager.GetString("suggestionShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string supervisor {
            get {
                return ResourceManager.GetString("supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender deadline.
        /// </summary>
        public static string tenderDeadline {
            get {
                return ResourceManager.GetString("tenderDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline for questions and answers.
        /// </summary>
        public static string tenderQA {
            get {
                return ResourceManager.GetString("tenderQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender sum (excl. tax).
        /// </summary>
        public static string tenderSumExclTax {
            get {
                return ResourceManager.GetString("tenderSumExclTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tender sum (incl. Tax).
        /// </summary>
        public static string tenderSumInclTax {
            get {
                return ResourceManager.GetString("tenderSumInclTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client&apos;s contact person during procurement time.
        /// </summary>
        public static string theClientsContactPersonTender {
            get {
                return ResourceManager.GetString("theClientsContactPersonTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time month.
        /// </summary>
        public static string timeMonth {
            get {
                return ResourceManager.GetString("timeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Co2.
        /// </summary>
        public static string totalCo2 {
            get {
                return ResourceManager.GetString("totalCo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total net cost.
        /// </summary>
        public static string totalNetCost {
            get {
                return ResourceManager.GetString("totalNetCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperNote.
        /// </summary>
        public static string UpperNote {
            get {
                return ResourceManager.GetString("UpperNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VVS.
        /// </summary>
        public static string VVS {
            get {
                return ResourceManager.GetString("VVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string waste {
            get {
                return ResourceManager.GetString("waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity completed.
        /// </summary>
        public static string workedQ {
            get {
                return ResourceManager.GetString("workedQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity completed (%).
        /// </summary>
        public static string workedQPercent {
            get {
                return ResourceManager.GetString("workedQPercent", resourceCulture);
            }
        }

        public static string calculationStatus          => ResourceManager.GetString("calculationStatus", resourceCulture)!;
        public static string addNewStatus               => ResourceManager.GetString("addNewStatus", resourceCulture)!;
        public static string newStatus                  => ResourceManager.GetString("newStatus", resourceCulture)!;
        public static string approvesAndLocksCalculation => ResourceManager.GetString("approvesAndLocksCalculation", resourceCulture)!;
        public static string allowsProductionCalculation => ResourceManager.GetString("allowsProductionCalculation", resourceCulture)!;
        public static string showHiddenStatuses           => ResourceManager.GetString("showHiddenStatuses", resourceCulture)!;
        public static string hideHiddenStatuses           => ResourceManager.GetString("hideHiddenStatuses", resourceCulture)!;
        public static string noHiddenStatusesToShow          => ResourceManager.GetString("noHiddenStatusesToShow", resourceCulture)!;
        public static string matchType                       => ResourceManager.GetString("matchType", resourceCulture)!;
        public static string matchSmart                      => ResourceManager.GetString("matchSmart", resourceCulture)!;
        public static string matchContains                   => ResourceManager.GetString("matchContains", resourceCulture)!;
        public static string matchEquals                     => ResourceManager.GetString("matchEquals", resourceCulture)!;
        public static string matchNotEquals                  => ResourceManager.GetString("matchNotEquals", resourceCulture)!;
        public static string matchSimilar                    => ResourceManager.GetString("matchSimilar", resourceCulture)!;
        public static string similarResults                  => ResourceManager.GetString("similarResults", resourceCulture)!;
        public static string similarMatchBadge               => ResourceManager.GetString("similarMatchBadge", resourceCulture)!;
        public static string matchStartsWith                 => ResourceManager.GetString("matchStartsWith", resourceCulture)!;
        public static string matchEndsWith                   => ResourceManager.GetString("matchEndsWith", resourceCulture)!;
        public static string matchSmartTip                   => ResourceManager.GetString("matchSmartTip", resourceCulture)!;
        public static string matchInfoTooltip                => ResourceManager.GetString("matchInfoTooltip", resourceCulture)!;
        public static string matchContainsTip                => ResourceManager.GetString("matchContainsTip", resourceCulture)!;
        public static string matchEqualsTip                  => ResourceManager.GetString("matchEqualsTip", resourceCulture)!;
        public static string matchStartsWithTip              => ResourceManager.GetString("matchStartsWithTip", resourceCulture)!;
        public static string matchEndsWithTip                => ResourceManager.GetString("matchEndsWithTip", resourceCulture)!;
        public static string matchSimilarTip                 => ResourceManager.GetString("matchSimilarTip", resourceCulture)!;
        public static string includeArchived                 => ResourceManager.GetString("includeArchived", resourceCulture)!;
        public static string typeFilter                      => ResourceManager.GetString("typeFilter", resourceCulture)!;
        public static string allTypes                        => ResourceManager.GetString("allTypes", resourceCulture)!;
        public static string foldersLabel                    => ResourceManager.GetString("foldersLabel", resourceCulture)!;
        public static string projectsLabel                   => ResourceManager.GetString("projectsLabel", resourceCulture)!;
        public static string calculationsLabel               => ResourceManager.GetString("calculationsLabel", resourceCulture)!;
        public static string noResultsFound                  => ResourceManager.GetString("noResultsFound", resourceCulture)!;
        public static string checkSpellingOrFilter           => ResourceManager.GetString("checkSpellingOrFilter", resourceCulture)!;
        public static string searchFoldersProjectsCalcs      => ResourceManager.GetString("searchFoldersProjectsCalcs", resourceCulture)!;
        public static string searchNameOrCodePlaceholder     => ResourceManager.GetString("searchNameOrCodePlaceholder", resourceCulture)!;
        public static string resultSummaryFormat               => ResourceManager.GetString("resultSummaryFormat", resourceCulture)!;
        public static string lockedAndApproved                 => ResourceManager.GetString("lockedAndApproved", resourceCulture)!;
        public static string lockedBecauseApproved             => ResourceManager.GetString("lockedBecauseApproved", resourceCulture)!;
        public static string approvedBy                        => ResourceManager.GetString("approvedBy", resourceCulture)!;
        public static string approvedDate                      => ResourceManager.GetString("approvedDate", resourceCulture)!;
        public static string unknownUser                       => ResourceManager.GetString("unknownUser", resourceCulture)!;
        public static string addNote                           => ResourceManager.GetString("addNote", resourceCulture)!;
        public static string approveAndLockTitle               => ResourceManager.GetString("approveAndLockTitle", resourceCulture)!;
        public static string approveAndLockDescription         => ResourceManager.GetString("approveAndLockDescription", resourceCulture)!;
        public static string approveAndLock                    => ResourceManager.GetString("approveAndLock", resourceCulture)!;
        public static string approvalBlockedNoResponsible      => ResourceManager.GetString("approvalBlockedNoResponsible", resourceCulture)!;
        public static string approvalBlockedInspectorOnly      => ResourceManager.GetString("approvalBlockedInspectorOnly", resourceCulture)!;
        public static string approvalBlockedResponsibleOnly    => ResourceManager.GetString("approvalBlockedResponsibleOnly", resourceCulture)!;
    }
}
