//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Adminstrator.Shared.ResourceFiles.Identity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceIdentity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceIdentity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagement.Adminstrator.Shared.ResourceFiles.Identity.ResourceIdentity", typeof(ResourceIdentity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string addUser {
            get {
                return ResourceManager.GetString("addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Nr.
        /// </summary>
        public static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your confirmation password does not match the new password. Please try again..
        /// </summary>
        public static string confirmPasswordNotMatchNewPasswordMsg {
            get {
                return ResourceManager.GetString("confirmPasswordNotMatchNewPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer groups.
        /// </summary>
        public static string customerGroup {
            get {
                return ResourceManager.GetString("customerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email and password do not match. Please try again..
        /// </summary>
        public static string emailPasswordNotmatchMsg {
            get {
                return ResourceManager.GetString("emailPasswordNotmatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax number.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First DisplayName.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID-Number.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout.
        /// </summary>
        public static string lockout {
            get {
                return ResourceManager.GetString("lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lockoutEnd.
        /// </summary>
        public static string lockoutEnd {
            get {
                return ResourceManager.GetString("lockoutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout Start.
        /// </summary>
        public static string lockoutStart {
            get {
                return ResourceManager.GetString("lockoutStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string logoutConfirmMsg {
            get {
                return ResourceManager.GetString("logoutConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manger.
        /// </summary>
        public static string Manger {
            get {
                return ResourceManager.GetString("Manger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password cannot be the same as your current password..
        /// </summary>
        public static string newPasswordCannotBeurrentPasswordMsg {
            get {
                return ResourceManager.GetString("newPasswordCannotBeurrentPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number ID Cards.
        /// </summary>
        public static string numberIDCards {
            get {
                return ResourceManager.GetString("numberIDCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string passwordForget {
            get {
                return ResourceManager.GetString("passwordForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters. Passwords must contain characters from three of the following four categories:
        ///1.	Lower case letter (a-z)
        ///2.	Upper case letter (A-Z)
        ///3.	Numeric character (0-9)
        ///4.	Special character (!,@,$,#,%,&amp;,*,=,-).
        /// </summary>
        public static string passwordRequirementsMsg {
            get {
                return ResourceManager.GetString("passwordRequirementsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully! Please click here to login..
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person/Organisation nr..
        /// </summary>
        public static string PersonOrganisationNr {
            get {
                return ResourceManager.GetString("PersonOrganisationNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person/Organisation QuestionKind.
        /// </summary>
        public static string PersonOrganisationType {
            get {
                return ResourceManager.GetString("PersonOrganisationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Confirmed.
        /// </summary>
        public static string phoneNumberConfirmed {
            get {
                return ResourceManager.GetString("phoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string PleaseCheckYourEmailToResetYourPassword_ {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmailToResetYourPassword.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a department.
        /// </summary>
        public static string PleaseSelectDepartment {
            get {
                return ResourceManager.GetString("PleaseSelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me..
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Manger.
        /// </summary>
        public static string SuperManger {
            get {
                return ResourceManager.GetString("SuperManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string sureLogoutMsg {
            get {
                return ResourceManager.GetString("sureLogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data is updated.
        /// </summary>
        public static string UserDataIsUpdated {
            get {
                return ResourceManager.GetString("UserDataIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string zipCode {
            get {
                return ResourceManager.GetString("zipCode", resourceCulture);
            }
        }
    }
}
