//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Adminstrator.Shared.ResourceFiles.AppControll {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppControll {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppControll() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagement.Adminstrator.Shared.ResourceFiles.AppControll.AppControll", typeof(AppControll).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Keyword.
        /// </summary>
        public static string addKeyWord {
            get {
                return ResourceManager.GetString("addKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administrators.
        /// </summary>
        public static string appUsers {
            get {
                return ResourceManager.GetString("appUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind Cap with Group.
        /// </summary>
        public static string bindCapGroup {
            get {
                return ResourceManager.GetString("bindCapGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string block {
            get {
                return ResourceManager.GetString("block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockout.
        /// </summary>
        public static string blockout {
            get {
                return ResourceManager.GetString("blockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing a web-based platform for construction and infrastructure companies to estimate project costs and manage project workflows efficiently..
        /// </summary>
        public static string BusinessActivity {
            get {
                return ResourceManager.GetString("BusinessActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind Cap with Resource .
        /// </summary>
        public static string capResourceBind {
            get {
                return ResourceManager.GetString("capResourceBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap Role.
        /// </summary>
        public static string capRole {
            get {
                return ResourceManager.GetString("capRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block the user?.
        /// </summary>
        public static string confirmTenantBlock {
            get {
                return ResourceManager.GetString("confirmTenantBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unblock the user?.
        /// </summary>
        public static string confirmTenantBlockout {
            get {
                return ResourceManager.GetString("confirmTenantBlockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expire.
        /// </summary>
        public static string dateExpire {
            get {
                return ResourceManager.GetString("dateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Db {
            get {
                return ResourceManager.GetString("Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete older from Month-Day.
        /// </summary>
        public static string Delete_older_from_Month_Day {
            get {
                return ResourceManager.GetString("Delete older from Month-Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        public static string expire {
            get {
                return ResourceManager.GetString("expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Own Database.
        /// </summary>
        public static string hasOwnDb {
            get {
                return ResourceManager.GetString("hasOwnDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string keyWord {
            get {
                return ResourceManager.GetString("keyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Calculations.
        /// </summary>
        public static string maxCalculations {
            get {
                return ResourceManager.GetString("maxCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Users.
        /// </summary>
        public static string maxUsers {
            get {
                return ResourceManager.GetString("maxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} from {1} ?.
        /// </summary>
        public static string msgRemoveBind__0___1_ {
            get {
                return ResourceManager.GetString("msgRemoveBind {0} {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We respect your privacy. Your data is stored securely and not shared with third parties unless required by law..
        /// </summary>
        public static string PrivacyContent {
            get {
                return ResourceManager.GetString("PrivacyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Bind {0} from {1}.
        /// </summary>
        public static string removeBind__0___1_ {
            get {
                return ResourceManager.GetString("removeBind {0} {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Licenses.
        /// </summary>
        public static string TabLicenses {
            get {
                return ResourceManager.GetString("TabLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string TabPrivacy {
            get {
                return ResourceManager.GetString("TabPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TabTerms {
            get {
                return ResourceManager.GetString("TabTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string tenant {
            get {
                return ResourceManager.GetString("tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use
        ///Effective Date: July 2025
        ///
        ///Welcome to Atasoft. By accessing or using our platform, you agree to the following terms and conditions. Please read them carefully before proceeding.
        ///
        ///1. Eligibility
        ///This service is primarily designed for construction and infrastructure companies. However, individuals may register and use the platform. By using the service, you confirm that you are at least 18 years old and authorized to represent your organization if applicable.
        ///
        ///2. Purpose of the Service
        ///O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TermsContent {
            get {
                return ResourceManager.GetString("TermsContent", resourceCulture);
            }
        }
    }
}
