//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Adminstrator.Shared.ResourceFiles.APP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagement.Adminstrator.Shared.ResourceFiles.APP.ResourceApp", typeof(ResourceApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string _new {
            get {
                return ResourceManager.GetString("_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string _private {
            get {
                return ResourceManager.GetString("_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string _public {
            get {
                return ResourceManager.GetString("_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align-Item.
        /// </summary>
        public static string alignItems {
            get {
                return ResourceManager.GetString("alignItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Please try again later..
        /// </summary>
        public static string AnUnexpectedErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string attribute {
            get {
                return ResourceManager.GetString("attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Type.
        /// </summary>
        public static string attributeType {
            get {
                return ResourceManager.GetString("attributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string background {
            get {
                return ResourceManager.GetString("background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string bold {
            get {
                return ResourceManager.GetString("bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolder.
        /// </summary>
        public static string bolder {
            get {
                return ResourceManager.GetString("bolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string border {
            get {
                return ResourceManager.GetString("border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Type.
        /// </summary>
        public static string borderType {
            get {
                return ResourceManager.GetString("borderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {0} must be between 0 and 999..
        /// </summary>
        public static string CapWasteValid__0_ {
            get {
                return ResourceManager.GetString("CapWasteValid {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string cell {
            get {
                return ResourceManager.GetString("cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully!.
        /// </summary>
        public static string completedSuccessfully {
            get {
                return ResourceManager.GetString("completedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string defaultValue {
            get {
                return ResourceManager.GetString("defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Delete this?.
        /// </summary>
        public static string deleteConfirmMsg {
            get {
                return ResourceManager.GetString("deleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Delete {0}?.
        /// </summary>
        public static string deleteConfirmMsg__0_ {
            get {
                return ResourceManager.GetString("deleteConfirmMsg {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department folders.
        /// </summary>
        public static string depSharedFolders {
            get {
                return ResourceManager.GetString("depSharedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the list in database?.
        /// </summary>
        public static string DoYouWanTtoSaveTheListInDatabase {
            get {
                return ResourceManager.GetString("DoYouWanTtoSaveTheListInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning.
        /// </summary>
        public static string earning {
            get {
                return ResourceManager.GetString("earning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font-Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Weight.
        /// </summary>
        public static string fontWeight {
            get {
                return ResourceManager.GetString("fontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been Updated.
        /// </summary>
        public static string HasBeedUpdated {
            get {
                return ResourceManager.GetString("HasBeedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been added.
        /// </summary>
        public static string HasBeenAdded {
            get {
                return ResourceManager.GetString("HasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully.
        /// </summary>
        public static string hasBeenAddedSuccessfully__0_ {
            get {
                return ResourceManager.GetString("hasBeenAddedSuccessfully {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully.
        /// </summary>
        public static string hasBeenDeletedSuccessfully__0_ {
            get {
                return ResourceManager.GetString("hasBeenDeletedSuccessfully {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been removed.
        /// </summary>
        public static string HasBeenRemoved {
            get {
                return ResourceManager.GetString("HasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully.
        /// </summary>
        public static string hasBeenUpdatedSuccessfully__0_ {
            get {
                return ResourceManager.GetString("hasBeenUpdatedSuccessfully {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden items.
        /// </summary>
        public static string hiddenItems {
            get {
                return ResourceManager.GetString("hiddenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0}.
        /// </summary>
        public static string import__0_ {
            get {
                return ResourceManager.GetString("import {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from File.
        /// </summary>
        public static string importFromFile {
            get {
                return ResourceManager.GetString("importFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Visible?.
        /// </summary>
        public static string isVisible {
            get {
                return ResourceManager.GetString("isVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is currently in use and cannot be deleted..
        /// </summary>
        public static string ItemIsCurrentlyInUseCannotBeDeleted_ {
            get {
                return ResourceManager.GetString("ItemIsCurrentlyInUseCannotBeDeleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string lastUpdate {
            get {
                return ResourceManager.GetString("lastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin-Bottom.
        /// </summary>
        public static string marginBottom {
            get {
                return ResourceManager.GetString("marginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin-Left.
        /// </summary>
        public static string marginLeft {
            get {
                return ResourceManager.GetString("marginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin-Top.
        /// </summary>
        public static string marginTop {
            get {
                return ResourceManager.GetString("marginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        public static string maxValue {
            get {
                return ResourceManager.GetString("maxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        public static string minValue {
            get {
                return ResourceManager.GetString("minValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string new__0_ {
            get {
                return ResourceManager.GetString("new {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string newItem {
            get {
                return ResourceManager.GetString("newItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string organisation {
            get {
                return ResourceManager.GetString("organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small-Left.
        /// </summary>
        public static string paddingLeft {
            get {
                return ResourceManager.GetString("paddingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small-Top.
        /// </summary>
        public static string paddingTop {
            get {
                return ResourceManager.GetString("paddingTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string parameter {
            get {
                return ResourceManager.GetString("parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some errors.
        /// </summary>
        public static string rangeErrors {
            get {
                return ResourceManager.GetString("rangeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder.
        /// </summary>
        public static string reOrder {
            get {
                return ResourceManager.GetString("reOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        public static string setAsDefault {
            get {
                return ResourceManager.GetString("setAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share and permissions.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start from row.
        /// </summary>
        public static string StartFromRow {
            get {
                return ResourceManager.GetString("StartFromRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string supervisor {
            get {
                return ResourceManager.GetString("supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Are No Items To Display.
        /// </summary>
        public static string ThereAreNoItemsToDisplay {
            get {
                return ResourceManager.GetString("ThereAreNoItemsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no elements.
        /// </summary>
        public static string thereIsNoElements {
            get {
                return ResourceManager.GetString("thereIsNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Compensation.
        /// </summary>
        public static string typeOfCompensation {
            get {
                return ResourceManager.GetString("typeOfCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Contact Company.
        /// </summary>
        public static string UnderContactCompany {
            get {
                return ResourceManager.GetString("UnderContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        public static string unkown {
            get {
                return ResourceManager.GetString("unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string update__0_ {
            get {
                return ResourceManager.GetString("update {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string visible {
            get {
                return ResourceManager.GetString("visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible items.
        /// </summary>
        public static string visibleItems {
            get {
                return ResourceManager.GetString("visibleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
