// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ConditionResourceRequirementDto
{
    //public int Id { get; set; }
    //public int QuestionConditionId { get; set; }
    //public int ResourceOptionGroupId { get; set; }
    public int ResourceOptionItemId { get; set; }
    public int SetKey { get; set; } = 1;
}