// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ConditionVariableRequirementDto
{
    public int Id { get; set; }
    public int QuestionConditionId { get; set; }
    public string VariableName { get; set; } = string.Empty;
    public decimal? MinAllowedValue { get; set; }
    public decimal? MaxAllowedValue { get; set; }
    public int SetKey { get; set; } = 1;
}
