// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ConditionOptionRequirementDto
{
    //public int Id { get; set; }
    public int SetKey { get; set; } = 1;

    //public int QuestionConditionId { get; set; }
    //public int OptionGroupId { get; set; }
    public int OptionItemId { get; set; }
}