// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ConditionNumericRequirementDto
{
    public int NumericInputId { get; set; }
    public decimal? MaxAllowedValue { get; set; }
    public decimal? MinAllowedValue { get; set; }
    public int SetKey { get; set; } = 1;
}