// <auto-generated> Generated from Entities for DTO usage. </auto-generated>
namespace ProjectManagement.Shared.DTO.ProjectAppStorage;

public class ConditionVariableRequirementDto
{
    public int Id { get; set; }
    public int QuestionConditionId { get; set; }
    public string? VariableName { get; set; }
    public double? MinAllowedValue { get; set; }
    public double? MaxAllowedValue { get; set; }
}