<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\UnitOfWork\**" />
    <EmbeddedResource Remove="Repositories\UnitOfWork\**" />
    <None Remove="Repositories\UnitOfWork\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <ProjectReference Include="..\ProjectManagement.Shared\ProjectManagement.Shared.csproj" />
  </ItemGroup>

</Project>
